default_context:
  project_name: 'TraderLab'
  project_slug: 'traderlab'
  domain_main: 'traderlab.com'
  domain_staging: 'stag.traderlab.com'
  docker_swarm_stack_name_main: 'traderlab-com'
  docker_swarm_stack_name_staging: 'stag-traderlab-com'
  secret_key: '972acddf000a2f43bed17276cedf50a8041435dea39be8ccbfbe889a13e6ecab'
  first_superuser: 'admin@traderlab.com'
  first_superuser_password: '031297'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.traderlab.com", "https://stag.traderlab.com", "https://traderlab.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@traderlab.com'
  postgres_password: '031297'
  pgadmin_default_user: 'admin@traderlab.com'
  pgadmin_default_user_password: '031297'
  traefik_constraint_tag: 'traderlab.com'
  traefik_constraint_tag_staging: 'stag.traderlab.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:031297'
  sentry_dsn: ''
  docker_image_prefix: 'traderlab/'
  docker_image_backend: 'traderlab/backend'
  docker_image_celeryworker: 'traderlab/celeryworker'
  docker_image_frontend: 'traderlab/frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
