"""Add column pickled_model to Item model

Revision ID: 5d6c5637559f
Revises: d4867f3a4c0a
Create Date: 2020-11-05 23:27:44.213309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6c5637559f'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('pickled_model', sa.PickleType(), nullable=True))
    op.create_index(op.f('ix_item_pickled_model'), 'item', ['pickled_model'], unique=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_item_pickled_model'), table_name='item')
    op.drop_column('item', 'pickled_model')
    # ### end Alembic commands ###
