"""Changed column pickled_model type in Item model to LargeBinary

Revision ID: 8b3921da29d6
Revises: 5d6c5637559f
Create Date: 2020-11-06 02:47:12.053502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b3921da29d6'
down_revision = '5d6c5637559f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
