"""Changed colum pickled_model in Item model back to PickleType

Revision ID: f0ececc2fb61
Revises: 8b3921da29d6
Create Date: 2020-11-06 03:22:25.996001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ececc2fb61'
down_revision = '8b3921da29d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
